[build]
command = "pnpm run build"
publish = "dist"

# 開発環境の設定
[dev]
targetPort = 4321
port = 8000
command = "pnpm astro dev"

[context.dev.environment]
NODE_ENV = "development"
OG_IMAGE_SIGNATURE_KEY = "this_is_a_secret_key"

# リダイレクト設定
[[redirects]]
from = "/projects"
to = "/#created-websites"

[[redirects]]
from = "/skills"
to = "/#skills"

[[redirects]]
from = "/privacy-policy"
to = "/policies/privacy"
