name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run linter
        run: pnpm run lint

  deploy-preview:
    name: Deploy to preview
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref != 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to preview
        id: deploy-result
        shell: /usr/bin/bash {0}
        # 参考: https://github.com/netlify/actions/blob/3eff4d5cd9bf9f7ba528c1f1bbb94a37c3a3201d/cli/entrypoint.sh
        run: |
          OUTPUT=$(pnpm netlify deploy --build --context deploy-preview 2>&1)
          COMMAND_EXIT_CODE=$?

          if [ $COMMAND_EXIT_CODE -ne 0 ]; then
            echo "$OUTPUT"
            exit $COMMAND_EXIT_CODE
          fi

          NETLIFY_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*(--)[a-zA-Z0-9./?=_-]*')

          echo "url=$NETLIFY_URL" >> $GITHUB_OUTPUT

          delimiter="$(openssl rand -hex 8)"
          echo "logs_url<<$delimiter" >> "$GITHUB_OUTPUT"
          echo "$OUTPUT" | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*' >> "$GITHUB_OUTPUT"
          echo "$delimiter" >> "$GITHUB_OUTPUT"

          echo "$OUTPUT"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          OG_IMAGE_SIGNATURE_KEY: ${{ secrets.OG_IMAGE_SIGNATURE_KEY_PREVIEW }}

      - name: Comment to commit
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        if: github.event_name == 'push'
        with:
          script: |
            const liveUrl = process.env.NETLIFY_URL;
            const logsUrl = process.env.NETLIFY_LOGS_URL;

            github.rest.repos.createCommitComment({
              ...context.repo,
              commit_sha: context.sha,
              body: [
                `# Deployed to ${liveUrl}`,
                '## Logs',
                ...logsUrl.split('\n').map(url => `- ${url}`)
              ].join('\n')
            });
        env:
          NETLIFY_URL: ${{ steps.deploy-result.outputs.url }}
          NETLIFY_LOGS_URL: ${{ steps.deploy-result.outputs.logs_url }}

      - name: Comment to Pull Request
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3
        with:
          comment-tag: netlify-deploy-preview
          mode: recreate
          message: |
            # Deployed to ${{ steps.deploy-result.outputs.url }}
            ## Logs
            ${{ steps.deploy-result.outputs.logs_url }}

  deploy-prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to production
        id: deploy-result
        shell: /usr/bin/bash {0}
        # 参考: https://github.com/netlify/actions/blob/3eff4d5cd9bf9f7ba528c1f1bbb94a37c3a3201d/cli/entrypoint.sh
        run: |
          OUTPUT=$(pnpm netlify deploy --prod --build --context production 2>&1)
          COMMAND_EXIT_CODE=$?

          if [ $COMMAND_EXIT_CODE -ne 0 ]; then
            echo "$OUTPUT"
            exit $COMMAND_EXIT_CODE
          fi

          NETLIFY_URL=$(echo "$OUTPUT" | grep 'Website URL:' | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*')

          echo "url=$NETLIFY_URL" >> $GITHUB_OUTPUT

          delimiter="$(openssl rand -hex 8)"
          echo "logs_url<<$delimiter" >> "$GITHUB_OUTPUT"
          echo "$OUTPUT" | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*' >> "$GITHUB_OUTPUT"
          echo "$delimiter" >> "$GITHUB_OUTPUT"

          echo "$OUTPUT"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          OG_IMAGE_SIGNATURE_KEY: ${{ secrets.OG_IMAGE_SIGNATURE_KEY_PROD }}

      - name: Comment to commit
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8
        with:
          script: |
            const liveUrl = process.env.NETLIFY_URL;
            const logsUrl = process.env.NETLIFY_LOGS_URL;

            github.rest.repos.createCommitComment({
              ...context.repo,
              commit_sha: context.sha,
              body: [
                `# Deployed to ${liveUrl}`,
                '## Logs',
                ...logsUrl.split('\n').map(url => `- ${url}`)
              ].join('\n')
            });
        env:
          NETLIFY_URL: ${{ steps.deploy-result.outputs.url }}
          NETLIFY_LOGS_URL: ${{ steps.deploy-result.outputs.logs_url }}
