name: CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run formatter
        run: pnpm run format:check

      - name: Run linter
        run: pnpm run lint

  deploy-preview:
    name: Deploy to preview
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref != 'refs/heads/main'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to preview
        id: deploy-result
        # 参考: https://github.com/netlify/actions/blob/3eff4d5cd9bf9f7ba528c1f1bbb94a37c3a3201d/cli/entrypoint.sh
        run: |
          OUTPUT=$(sh -c "echo && pnpm netlify deploy --build")
          NETLIFY_LOGS_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*')
          NETLIFY_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*(--)[a-zA-Z0-9./?=_-]*')

          echo "url=$NETLIFY_URL" >> $GITHUB_OUTPUT
          echo "logs_url=$NETLIFY_LOGS_URL" >> $GITHUB_OUTPUT
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment to commit
        uses: actions/github-script@v7
        if: github.event_name == 'push'
        with:
          script: |
            const liveUrl = process.env.NETLIFY_URL;
            const logsUrl = process.env.NETLIFY_LOGS_URL;

            github.rest.repos.createCommitComment({
              ...context.repo,
              commit_sha: context.sha,
              body: `Deployed to ${liveUrl}\nLogs: ${logsUrl}`
            });
        env:
          NETLIFY_URL: ${{ steps.deploy-result.outputs.url }}
          NETLIFY_LOGS_URL: ${{ steps.deploy-result.outputs.logs_url }}

      - name: Comment to Pull Request
        if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v3
        with:
          comment-tag: 'netlify-deploy-preview'
          mode: recreate
          message: |
            Deployed to ${{ steps.deploy-result.outputs.url }}
            Logs: ${{ steps.deploy-result.outputs.logs_url }}

  deploy-prod:
    name: Deploy to production
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          node-version-file: .tool-versions
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Deploy to production
        id: deploy-result
        # 参考: https://github.com/netlify/actions/blob/3eff4d5cd9bf9f7ba528c1f1bbb94a37c3a3201d/cli/entrypoint.sh
        run: |
          OUTPUT=$(sh -c "echo && pnpm netlify deploy --prod --build")
          NETLIFY_LOGS_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*')
          NETLIFY_URL=$(echo "$OUTPUT" | grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*' | grep -Eov "netlify.com")

          echo "url=$NETLIFY_URL" >> $GITHUB_OUTPUT
          echo "logs_url=$NETLIFY_LOGS_URL" >> $GITHUB_OUTPUT
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment to commit
        uses: actions/github-script@v7
        with:
          script: |
            const liveUrl = process.env.NETLIFY_URL;
            const logsUrl = process.env.NETLIFY_LOGS_URL;

            github.rest.repos.createCommitComment({
              ...context.repo,
              commit_sha: context.sha,
              body: `Deployed to ${liveUrl}\nLogs: ${logsUrl}`
            });
        env:
          NETLIFY_URL: ${{ steps.deploy-result.outputs.url }}
          NETLIFY_LOGS_URL: ${{ steps.deploy-result.outputs.logs_url }}
